name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f184e5e51a2e7c4a9faeb607d2ded22647e5b8027cd557ab405cc76bc4a4f29"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
