name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3485b4cd81612495e8692f41bd4e63a11d8e92cc13e418cac973baff557c7b07"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
