name = "Pack"
author = "ripSquid, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37abf3339623da4c425b1cdd9e4c235ed44c4c5f3fdef6912b55b85faba01f16"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
