name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f713f5ba721598d91f2290e2bd956a92a8543fadeba956b33a250b73f19e4c2"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
