name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cf856508d5ac2c46db7594e7262c313e05a86807a4cf04e4fa8e44031c104f0"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
