name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ecdf9fa69133b67300116a8488a3342ff1b6fb2e36dee3a89f6ae19bae4eb21"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
