name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2bc9b11e3c568ce121e2980226bdc0175a1d413d0b3b4104de0397b029ab529"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
