name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a327fc0bbf98240be48cfb8a544dfdb8f4fcad766ac4df1bdff1c499e23aa508"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
