name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d67d888222fa1bb571af341f35bfdf91fa2b2fdccff093fce6b7ac0b7f2ef31f"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
