name = "Pack"
author = "ripSquid, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f7b355950a8c2ca476dde6a5737b75ac8bc6acabadc62935e5ad9abcd785b3a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
