name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a7618640d995a4a664ac5d17324dfa77f904a90d3aaf27225701cdc012fbf65"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
