name = "Pack"
author = "ripSquid, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64bb0b02d7f1aaad7f687eea852624d279e1bf7cfbd9cce0133547f3dcb95018"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
