name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc2c9dda19f1939e68615e0cc683a7d0e75586d66dfea131d3867afc9f621336"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
