name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeaed0b5c508358e9c11374ccf26860135019e601f440fb8e082e716d1b7fc05"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
