name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ec1ad32cc37ee27d74fe20b0bd8184f4b4233a24df192ba722dfe01ce1bc78"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
