name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb27ee13abdab3a314032a0a3360adb80076ec810232deff3b2516dbfd7571c2"

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.4"]
