name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c55fd1efb51c3e3e9a313fc7d6b3587d59d4b118a0dd33b05fd7cc6b38690fe"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
