name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f8613859252fefdfc4bd1bfa42ca9a9101b09c70f4c8f19bd4fc50a226a46f7"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
