name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c31afebad711775564eb3438c7e0dd73767efef1d1e0ca4bd1d1e1aec0799c78"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
