name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bcafd6f8eb40cfa8b6fc9c1f6edf7fb25b2bfe88fee87996363658338cf7d42"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
