name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80c02fbcfaf24e3df030ed6495444804874af38710e4305d6bf21cbcd6daa87d"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
