name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc06af6318c83194f19b0cd7b5e3f815a711bd5d71ce458fb687447942780761"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
