name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "892cba368dbbf5c309d27f5a7e50627dc6503e3acf2b1551065f3f885f2eb4d1"

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.4"]
