name = "Pack"
author = "ripSquidd, AvonOfficial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "761f27c40f4b65d336a0317defc66affbe2a11e9d66370b289b58e30f619e05a"

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
