name = "Bolibompa Create"
author = "ripSquid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "274225ac73a16d6fcaa2ebba3faefc0fab7cbe8f15218de6e3a010ab709a2af8"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
